;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #0c0e0f
background-alt = #151515
primary = #FFF
alert = #e8646a

[bar/top]
width = 100%
height = 24pt
background = ${colors.background}
line-size = 3pt
padding-left = 0
padding-right = 2
module-margin = 1
font-0 = JetBrainsMono Nerd Font;2
modules-left = bspwm xwindow
modules-right = date pulseaudio
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true
wm-restack = bspwm

[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt

[module/bspwm]
type = internal/bspwm

label-focused = %index%
label-focused-background = ${colors.background-alt}
label-focused-padding = 1

label-occupied = %index%
label-occupied-padding = 1

label-urgent = %index%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = 
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:30:...%

[module/pulseaudio]
type = internal/pulseaudio

format-volume =  <label-volume>

label-volume = %percentage%%

label-muted = muted

[module/date]
type = internal/date
interval = 5

date = "%a %b %d"
time = %H:%M

format =  <label>
label = %time% %date%

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
